FROM node:20-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
# RUN npm install -D @swc/cli @swc/core
RUN npm i

FROM base AS runner
WORKDIR /app
ENV NODE_ENV development

RUN if ! id "nextjs" &>/dev/null; then \
  addgroup --system --gid 1002 nodejs && \
  adduser --system --ingroup nodejs nextjs; \
  fi

COPY --from=deps /app/node_modules ./node_modules
COPY ./public /app/public
COPY . .

RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3002

CMD ["npm", "run", "dev", "--", "-p", "3002"]