FROM node:20-alpine

WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY package.json package-lock.json ./
RUN npm i
COPY . .

ENV NODE_ENV developdment

EXPOSE 3001

CMD ["npm", "run", "dev", "--", "-p", "3001"]
